name: interpret
channels:
  - defaults
dependencies:
  - matplotlib=3.1*
  - numpy=1.17*
  - pandas=0.25*
  - pip=19.3*
  - python=3.7
  - scikit-learn=0.22.*
  - seaborn=0.9*
  - pip:
    - altair>=4.0
    - lime==0.1.1.36
    - pyarrow>=0.15
    - shap==0.33.0
    - stratx==0.1.3
    - streamlit>=0.52
